### ISSUE TITLE
[Meta] Substrate IBC Completion guide

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/centauri#72]
This a  tracking issue for the issues that need to be completed to get the ibc implementation on substrate to the finish line.
More issues will be added as time passes.

## Ibc-rs
- [x] https://github.com/ComposableFi/ibc-rs/issues/37
- [x] https://github.com/ComposableFi/ibc-rs/issues/31
- [x] https://github.com/ComposableFi/ibc-rs/issues/32
- [x] https://github.com/ComposableFi/ibc-rs/issues/46
- [x] https://github.com/ComposableFi/ibc-rs/pull/57
- [x] https://github.com/ComposableFi/ibc-rs/pull/55
- [x]  https://github.com/ComposableFi/ibc-rs/issues/49

## Pallet Ibc
- [x] ~https://github.com/ComposableFi/composable/issues/1444~
- [ ] https://github.com/ComposableFi/centauri/issues/73
- [x] https://github.com/ComposableFi/composable/pull/1374

## Hyperspace
- [x] https://github.com/ComposableFi/hyperspace/pull/21
- [x] https://github.com/ComposableFi/centauri/issues/69
- [x] https://github.com/ComposableFi/centauri/issues/74
- [x] https://github.com/ComposableFi/centauri/issues/71
- [x] https://github.com/ComposableFi/centauri/issues/79

**Comment by akc2267** [comment]
nicely done!
